baseurl = "https://www.alumxi.com"
languageCode = "en-us"
theme = "terminal"
paginate = 2
publishDir = "docs"

[params]
# dir name of your blog content (default is `content/posts`)
contentTypeName = "posts"
# ["orange", "blue", "red", "green", "pink"]
themeColor = "pink"
# if you set this to 0, only submenu trigger will be visible
showMenuItems = 5
# show selector to switch language
showLanguageSelector = false
# set theme to full screen width
fullWidthTheme = false
# center theme with default width
centerTheme = true

# set a custom favicon (default is a `themeColor` square)
# favicon = "favicon.ico"
# set all headings to their default size (depending on browser settings)
# it's set to `true` by default
# oneHeadingSize = false
[languages]

[languages.en]
languageName = "English"
title = "Xi Chapter Alumni Association"
subtitle = "Website of the Alumni Association of Xi Chapter of Tau Epsilon Phi Fraternity at MIT."
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "AlumXi"
logoHomeLink = "/"

[languages.en.menu]

[[languages.en.menu.main]]
identifier = "membership"
name="Membership"
url = "/membership/alumxi"

[[languages.en.menu.main]]
identifier = "giving-alumxi"
name= "Donate!"
url = "/giving/alumxi"


[[languages.en.menu.main]]
identifier = "aboutNational"
name="TEP National"
url = "/about"

[[languages.en.menu.main]]
identifier = "capital-campaign"
name = "Capital Campaign"
url = "/giving/capital"

[[languages.en.menu.main]]
identifier = "events"
name = "Events"
url = "/events/current"

